language: node_js
sudo: required
os:
  - linux
node_js:
  - "7"

cache:
  directories:
  - node_modules # NPM packages

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
- npm install --silent
- npm run test:node
- npm run test:browser
- npm run test:typings
- npm run test:deps
- npm run build
- npm run lint
- (cd ./examples/angular2 && npm install --silent && npm run build && npm run test:build)
- (cd ./examples/vue && npm install --silent && npm run lint && npm run build && npm run test)
